SECTION "Mon Icons 1", ROMX

NullIcon:
AllileafIcon:     INCBIN "gfx/icons/allileaf.2bpp"
CrocofrondIcon:   INCBIN "gfx/icons/crocofrond.2bpp"
DracodileIcon:    INCBIN "gfx/icons/dracodile.2bpp"
LavasaurIcon:     INCBIN "gfx/icons/lavasaur.2bpp"
BrontosearIcon:   INCBIN "gfx/icons/brontosear.2bpp"
VolbrachioIcon:   INCBIN "gfx/icons/volbrachio.2bpp"
SharquaIcon:      INCBIN "gfx/icons/sharqua.2bpp"
CappiIcon:        INCBIN "gfx/icons/cappi.2bpp"
CapyboaraIcon:	  INCBIN "gfx/icons/capyboara.2bpp"
PebbirdIcon:      INCBIN "gfx/icons/pebbird.2bpp"
FeathoreIcon:     INCBIN "gfx/icons/feathore.2bpp"
BoulderocIcon:    INCBIN "gfx/icons/boulderoc.2bpp"
BuggyIcon:        INCBIN "gfx/icons/buggy.2bpp"
VaporetIcon:      INCBIN "gfx/icons/vaporet.2bpp"
FerrestormIcon:	  INCBIN "gfx/icons/ferrestorm.2bpp"
BunilopeIcon:	  INCBIN "gfx/icons/bunilope.2bpp"
BuniwolpIcon:     INCBIN "gfx/icons/buniwolp.2bpp"
PoliwagIcon:      INCBIN "gfx/icons/poliwag.2bpp"
JigglypuffIcon:   INCBIN "gfx/icons/jigglypuff.2bpp"
DiglettIcon:      INCBIN "gfx/icons/diglett.2bpp"
PikachuIcon:      INCBIN "gfx/icons/pikachu.2bpp"
StaryuIcon:       INCBIN "gfx/icons/staryu.2bpp"
FishIcon:         INCBIN "gfx/icons/fish.2bpp"
MonsterIcon:      INCBIN "gfx/icons/monster.2bpp"
ClefairyIcon:     INCBIN "gfx/icons/clefairy.2bpp"
OddishIcon:       INCBIN "gfx/icons/oddish.2bpp"
BugIcon:          INCBIN "gfx/icons/bug.2bpp"
GhostIcon:        INCBIN "gfx/icons/ghost.2bpp"

SECTION "Mon Icons 2", ROMX

SudowoodoIcon:    INCBIN "gfx/icons/sudowoodo.2bpp"
BigmonIcon:       INCBIN "gfx/icons/bigmon.2bpp"
FighterIcon:      INCBIN "gfx/icons/fighter.2bpp"
EggIcon:          INCBIN "gfx/icons/egg.2bpp"
JellyfishIcon:    INCBIN "gfx/icons/jellyfish.2bpp"
MothIcon:         INCBIN "gfx/icons/moth.2bpp"
BatIcon:          INCBIN "gfx/icons/bat.2bpp"
SnorlaxIcon:      INCBIN "gfx/icons/snorlax.2bpp"
HoOhIcon:         INCBIN "gfx/icons/ho_oh.2bpp"
LugiaIcon:        INCBIN "gfx/icons/lugia.2bpp"
GyaradosIcon:     INCBIN "gfx/icons/gyarados.2bpp"
SlowpokeIcon:     INCBIN "gfx/icons/slowpoke.2bpp"
LaprasIcon:       INCBIN "gfx/icons/lapras.2bpp"
HumanshapeIcon:   INCBIN "gfx/icons/humanshape.2bpp"
FoxIcon:          INCBIN "gfx/icons/fox.2bpp"
ShellIcon:        INCBIN "gfx/icons/shell.2bpp"
BlobIcon:         INCBIN "gfx/icons/blob.2bpp"
SerpentIcon:      INCBIN "gfx/icons/serpent.2bpp"
VoltorbIcon:      INCBIN "gfx/icons/voltorb.2bpp"
CaterpillarIcon:  INCBIN "gfx/icons/caterpillar.2bpp"
UnownIcon:        INCBIN "gfx/icons/unown.2bpp"
GeodudeIcon:      INCBIN "gfx/icons/geodude.2bpp"